name: samgeo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - qgis
  - geopandas
  - rasterio
  - shapely
  - gdal
  - flask
  - flask-cors
  - pip
  - pip:
    - -r requirements.txt 